name: Connect to Kubeflow Pipeline

on:
  push:
    branches: [ main ]

jobs:
  connect_to_kubeflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: your-region
        role-to-assume: arn:aws:iam::871927043079:role/GitHubAction-AssumeRoleWithAction
        role-duration-seconds: 3600
        role-session-name: GitHubActions

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: 871927043079.dkr.ecr.us-east-1.amazonaws.com/kubeflow
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Connect to Kubeflow Pipeline
    #   run: python connect_to_kubeflow.py  # replace with your script
